//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmrHisto.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CmrHisto.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here.
        /// </summary>
        internal static string ClickHere {
            get {
                return ResourceManager.GetString("ClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gradient {
            get {
                object obj = ResourceManager.GetObject("Gradient", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected to load a scale from a file. That option will be overridden if you select auto scale for that axis..
        /// </summary>
        internal static string LoadScaleFromFileOverrideWarning {
            get {
                return ResourceManager.GetString("LoadScaleFromFileOverrideWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ECT PID found, ECT limiting options have been disabled..
        /// </summary>
        internal static string LogMissingEctPid {
            get {
                return ResourceManager.GetString("LogMissingEctPid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your log did not contain any PIDs that will allow for PRATIO calculation. You must select a PID to use for the Y axis.
        ///
        ///.
        /// </summary>
        internal static string LogMissingRatioCalculationPid {
            get {
                return ResourceManager.GetString("LogMissingRatioCalculationPid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your log did not contain the PRATIO or P-RATIO MAP/BARO PIDs. P-Ratio will be calculated using AVG MAP TO USE / Baro.
        ///
        ///.
        /// </summary>
        internal static string LogMissingRatioPid {
            get {
                return ResourceManager.GetString("LogMissingRatioPid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom PID Error.
        /// </summary>
        internal static string MessageBoxCustomPidError {
            get {
                return ResourceManager.GetString("MessageBoxCustomPidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Error!.
        /// </summary>
        internal static string MessageBoxDataError {
            get {
                return ResourceManager.GetString("MessageBoxDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECT Error!.
        /// </summary>
        internal static string MessageBoxEctError {
            get {
                return ResourceManager.GetString("MessageBoxEctError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Error!.
        /// </summary>
        internal static string MessageBoxFileError {
            get {
                return ResourceManager.GetString("MessageBoxFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string MessageBoxGeneralError {
            get {
                return ResourceManager.GetString("MessageBoxGeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a valid number greater than 1 into the box..
        /// </summary>
        internal static string MessageBoxInvalidScale {
            get {
                return ResourceManager.GetString("MessageBoxInvalidScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom PID Added.
        /// </summary>
        internal static string MessageBoxPidAddedError {
            get {
                return ResourceManager.GetString("MessageBoxPidAddedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PID Error!.
        /// </summary>
        internal static string MessageBoxPidNotFoundError {
            get {
                return ResourceManager.GetString("MessageBoxPidNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Error!.
        /// </summary>
        internal static string MessageBoxProcessingError {
            get {
                return ResourceManager.GetString("MessageBoxProcessingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale Error!.
        /// </summary>
        internal static string MessageBoxScaleError {
            get {
                return ResourceManager.GetString("MessageBoxScaleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageBoxValueScaleError {
            get {
                return ResourceManager.GetString("MessageBoxValueScaleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom PID Already Exists!.
        /// </summary>
        internal static string MessageExistingPidError {
            get {
                return ResourceManager.GetString("MessageExistingPidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string One {
            get {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while the surface map is built..
        /// </summary>
        internal static string PleaseWaitForSurfaceMap {
            get {
                return ResourceManager.GetString("PleaseWaitForSurfaceMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture coordinate array not uploaded correctly.
        /// </summary>
        internal static string TextureCoodinatesNotUploaded {
            get {
                return ResourceManager.GetString("TextureCoodinatesNotUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error checking the version, please try again later..
        /// </summary>
        internal static string VersionCheckError {
            get {
                return ResourceManager.GetString("VersionCheckError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;You are running version {0} and the most recent version is {1}. To get the most recent version, &quot;.
        /// </summary>
        internal static string VersionNotCurrent {
            get {
                return ResourceManager.GetString("VersionNotCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the most up to date version of CmrHisto..
        /// </summary>
        internal static string VersionUpToDate {
            get {
                return ResourceManager.GetString("VersionUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Zero {
            get {
                return ResourceManager.GetString("Zero", resourceCulture);
            }
        }
    }
}
